### ISSUE TITLE
How to prevent a crash inside plugin screwing up the main pipeline ? 

### ISSUE THREAD

**Issue by blackball** [sourcey/pluga#2]
Hi, 

I am reading the implementation of pluga. I really like the clean interface and mechanism. 

But in order to be a reliable plugin framework, how does the core system prevent crashes caused by  3rd party plugins ?  I don't have a good idea right now. The only sane idea I can think of is making all plugins run in another process, then use IPC to communicate with.  But then the communication part will be complicated and an bottleneck for data intensive applications. 

Do you have any idea on this ? 

Thanks,

**Comment by auscaster** [comment]
This is achieved by loading the plugin as a shared library (dll or .so)

**Comment by blackball** [comment]
No, it's not. 

If the function you called from your plugin crashed (for example, segment fault), current program will crash as well.
